# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Build the library
    cmds:
      - lake build
    deps:
      - get-cache

  build-docs:
    desc: Build the docs
    sources:
      - ./**/*.lean
      - ./**/lakefile.toml
      - exclude: ./**/.lake
    generates:
      - docbuild/.lake/build/doc/SpecialNumbers.html
    method: checksum
    cmds:
      - rm -rf docbuild/.lake/build/doc/SpecialNumbers*
      - cd docbuild && lake build SpecialNumbers:docs
    deps:
      - get-cache

  serve-docs:
    desc: Serve documentation locally
    cmds:
      - python3 -m http.server -d docbuild/.lake/build/doc
    deps:
      - build-docs

  get-cache-for-dir:
    internal: true
    run: once
    dir: '{{.DIR | default "." }}'
    cmds:
      - lake exe cache get
    status:
      - test -f .lake/packages/mathlib/.lake/build/lib/Mathlib.olean
  
  get-cache:
    desc: Ensure Mathlib cache is available
    cmds:
      - for: [".", "docbuild"]
        task: get-cache-for-dir
        vars:
          DIR: '{{ .ITEM }}'