name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            docbuild/.lake/build/doc
            ~/.elan
          key: ${{ runner.os }}-website-cache-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-cache-

      # Build the static website using the Nix flake
      - name: Build docs
        run: nix develop -c task build-docs

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docbuild/.lake/build/doc
